# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SignP.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!

import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from Setting import Ui_MainWindow

class Ui_SignLanguageTranslator(object):

    def openWindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.window)
        SignLanguageTranslator.hide()
        self.window.show()

        
    def setupUi(self, SignLanguageTranslator):
        SignLanguageTranslator.setObjectName("SignLanguageTranslator")
        SignLanguageTranslator.resize(779, 550)
        self.centralwidget = QtWidgets.QWidget(SignLanguageTranslator)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(30, 50, 711, 431))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.scrollArea = QtWidgets.QScrollArea(self.tab_3)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 181, 301))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 179, 299))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame.setGeometry(QtCore.QRect(0, 0, 181, 31))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(10, 0, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        self.textBrowser.setGeometry(QtCore.QRect(0, 30, 181, 271))
        self.textBrowser.setObjectName("textBrowser")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.scrollAreaWidgetContents)
        self.tableWidget_2.setEnabled(True)
        self.tableWidget_2.setGeometry(QtCore.QRect(0, 30, 181, 271))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_2.sizePolicy().hasHeightForWidth())
        self.tableWidget_2.setSizePolicy(sizePolicy)
        self.tableWidget_2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tableWidget_2.setAutoFillBackground(True)
        self.tableWidget_2.setLineWidth(1)
        self.tableWidget_2.setMidLineWidth(0)
        self.tableWidget_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableWidget_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_2.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableWidget_2.setAutoScrollMargin(16)
        self.tableWidget_2.setAlternatingRowColors(False)
        self.tableWidget_2.setTextElideMode(QtCore.Qt.ElideRight)
        self.tableWidget_2.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget_2.setShowGrid(True)
        self.tableWidget_2.setCornerButtonEnabled(True)
        self.tableWidget_2.setRowCount(4)
        self.tableWidget_2.setColumnCount(1)
        self.tableWidget_2.setObjectName("tableWidget_2")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget_2.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget_2.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 0, item)
        self.tableWidget_2.horizontalHeader().setVisible(False)
        self.tableWidget_2.horizontalHeader().setHighlightSections(True)
        self.tableWidget_2.horizontalHeader().setMinimumSectionSize(19)
        self.tableWidget_2.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_2.verticalHeader().setVisible(False)
        self.tableWidget_2.verticalHeader().setHighlightSections(True)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.label = QtWidgets.QLabel(self.tab_3)
        self.label.setGeometry(QtCore.QRect(190, 290, 71, 31))
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(self.tab_3)
        self.textEdit.setGeometry(QtCore.QRect(190, 320, 461, 79))
        self.textEdit.setObjectName("textEdit")
        self.graphicsView = QtWidgets.QGraphicsView(self.tab_3)
        self.graphicsView.setGeometry(QtCore.QRect(190, 0, 461, 291))
        self.graphicsView.setObjectName("graphicsView")
        self.frame_6 = QtWidgets.QFrame(self.tab_3)
        self.frame_6.setGeometry(QtCore.QRect(0, 300, 181, 101))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.pushClear = QtWidgets.QPushButton(self.frame_6)
        self.pushClear.setGeometry(QtCore.QRect(50, 30, 91, 41))
        self.pushClear.setObjectName("pushClear")
        self.commandLinkButton_2 = QtWidgets.QCommandLinkButton(self.tab_3)
        self.commandLinkButton_2.setGeometry(QtCore.QRect(660, 0, 51, 51))
        self.commandLinkButton_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("setting.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.commandLinkButton_2.setIcon(icon)
        self.commandLinkButton_2.setIconSize(QtCore.QSize(30, 30))
        self.commandLinkButton_2.setCheckable(False)
        self.commandLinkButton_2.setObjectName("commandLinkButton_2")

        self.commandLinkButton_2.clicked.connect(self.openWindow)
        
        self.frame_6.raise_()
        self.scrollArea.raise_()
        self.label.raise_()
        self.textEdit.raise_()
        self.graphicsView.raise_()
        self.commandLinkButton_2.raise_()
        self.tabWidget.addTab(self.tab_3, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.tab)
        self.graphicsView_2.setGeometry(QtCore.QRect(190, 0, 461, 291))
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.meaining = QtWidgets.QPlainTextEdit(self.tab)
        self.meaining.setGeometry(QtCore.QRect(190, 320, 341, 79))
        self.meaining.setPlainText("")
        self.meaining.setObjectName("meaining")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(190, 290, 71, 31))
        self.label_5.setObjectName("label_5")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.tab)
        self.scrollArea_2.setGeometry(QtCore.QRect(0, 0, 181, 301))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 179, 299))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.frame_8 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.frame_8.setGeometry(QtCore.QRect(0, 0, 181, 31))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.label_6 = QtWidgets.QLabel(self.frame_8)
        self.label_6.setGeometry(QtCore.QRect(10, 0, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setAutoFillBackground(False)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_2)
        self.textBrowser_2.setGeometry(QtCore.QRect(0, 30, 181, 271))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.tableWidget = QtWidgets.QTableWidget(self.scrollAreaWidgetContents_2)
        self.tableWidget.setEnabled(True)
        self.tableWidget.setGeometry(QtCore.QRect(0, 30, 181, 271))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tableWidget.setAutoFillBackground(True)
        self.tableWidget.setLineWidth(1)
        self.tableWidget.setMidLineWidth(0)
        self.tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableWidget.setAutoScrollMargin(16)
        self.tableWidget.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.tableWidget.setAlternatingRowColors(False)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget.setTextElideMode(QtCore.Qt.ElideRight)
        self.tableWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setCornerButtonEnabled(True)
        self.tableWidget.setRowCount(1)
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(0, 0, item)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(19)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setHighlightSections(True)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.deletebtn = QtWidgets.QPushButton(self.tab)
        self.deletebtn.setGeometry(QtCore.QRect(30, 310, 111, 41))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../Desktop/3483/rubbish.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deletebtn.setIcon(icon1)
        self.deletebtn.setObjectName("deletebtn")
        self.allselect = QtWidgets.QPushButton(self.tab)
        self.allselect.setGeometry(QtCore.QRect(30, 350, 111, 41))
        self.allselect.setObjectName("allselect")
        self.commandLinkButton = QtWidgets.QCommandLinkButton(self.tab)
        self.commandLinkButton.setGeometry(QtCore.QRect(660, 0, 51, 51))
        self.commandLinkButton.setText("")
        self.commandLinkButton.setIcon(icon)
        self.commandLinkButton.setIconSize(QtCore.QSize(30, 30))
        self.commandLinkButton.setCheckable(False)
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.add = QtWidgets.QPushButton(self.tab)
        self.add.setGeometry(QtCore.QRect(540, 330, 81, 61))
        self.add.setObjectName("add")
        self.clear = QtWidgets.QPushButton(self.tab)
        self.clear.setGeometry(QtCore.QRect(620, 330, 81, 61))
        self.clear.setObjectName("clear")
        self.deletebtn.raise_()
        self.graphicsView_2.raise_()
        self.meaining.raise_()
        self.label_5.raise_()
        self.scrollArea_2.raise_()
        self.allselect.raise_()
        self.commandLinkButton.raise_()
        self.add.raise_()
        self.clear.raise_()
        self.tabWidget.addTab(self.tab, "")
        SignLanguageTranslator.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(SignLanguageTranslator)
        self.statusbar.setObjectName("statusbar")
        SignLanguageTranslator.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(SignLanguageTranslator)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 779, 22))
        self.menubar.setObjectName("menubar")
        self.menuSign_Language_Translator = QtWidgets.QMenu(self.menubar)
        self.menuSign_Language_Translator.setObjectName("menuSign_Language_Translator")
        SignLanguageTranslator.setMenuBar(self.menubar)
        self.menubar.addAction(self.menuSign_Language_Translator.menuAction())

        self.retranslateUi(SignLanguageTranslator)
        self.tabWidget.setCurrentIndex(1)
        self.add.clicked.connect(self.meaining.clear)
        self.allselect.clicked.connect(self.tableWidget.selectAll)
        self.deletebtn.clicked.connect(self.tableWidget.close)
        self.pushClear.clicked.connect(self.tableWidget_2.close)
        self.clear.clicked.connect(self.meaining.undo)
        QtCore.QMetaObject.connectSlotsByName(SignLanguageTranslator)

    def retranslateUi(self, SignLanguageTranslator):
        _translate = QtCore.QCoreApplication.translate
        SignLanguageTranslator.setWindowTitle(_translate("SignLanguageTranslator", "MainWindow"))
        self.label_2.setText(_translate("SignLanguageTranslator", "Previous Result:"))
        item = self.tableWidget_2.verticalHeaderItem(0)
        item.setText(_translate("SignLanguageTranslator", "word"))
        __sortingEnabled = self.tableWidget_2.isSortingEnabled()
        self.tableWidget_2.setSortingEnabled(False)
        item = self.tableWidget_2.item(0, 0)
        item.setText(_translate("SignLanguageTranslator", "壓力"))
        item = self.tableWidget_2.item(1, 0)
        item.setText(_translate("SignLanguageTranslator", "姓"))
        item = self.tableWidget_2.item(2, 0)
        item.setText(_translate("SignLanguageTranslator", "多謝你"))
        item = self.tableWidget_2.item(3, 0)
        item.setText(_translate("SignLanguageTranslator", "加"))
        self.tableWidget_2.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("SignLanguageTranslator", "Translated:"))
        self.textEdit.setHtml(_translate("SignLanguageTranslator", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.SF NS Text\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:24pt;\"><br /></p></body></html>"))
        self.pushClear.setText(_translate("SignLanguageTranslator", "Clear"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("SignLanguageTranslator", "Translate"))
        self.label_5.setText(_translate("SignLanguageTranslator", "Meaning:"))
        self.label_6.setText(_translate("SignLanguageTranslator", "Gestures that added:"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("SignLanguageTranslator", "word"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("SignLanguageTranslator", "傘"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.deletebtn.setText(_translate("SignLanguageTranslator", "Delete"))
        self.allselect.setText(_translate("SignLanguageTranslator", "Select All"))
        self.add.setText(_translate("SignLanguageTranslator", "Add"))
        self.clear.setText(_translate("SignLanguageTranslator", "Clear"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("SignLanguageTranslator", "Add Gesture"))
        self.menuSign_Language_Translator.setTitle(_translate("SignLanguageTranslator", "Sign Language Translator"))


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    SignLanguageTranslator = QtWidgets.QMainWindow()
    ui = Ui_SignLanguageTranslator()
    ui.setupUi(SignLanguageTranslator)
    SignLanguageTranslator.show()
    sys.exit(app.exec_())
